-d E:\datasheet\gowin\TangNano4k_examples-sipeed\camera_hdmi\impl\gwsynthesis\camera_hdmi.vg
-p GW1NSR-4C-QFN48P-6
-pn GW1NSR-LV4CQN48PC6/I5
-cst E:\datasheet\gowin\TangNano4k_examples-sipeed\camera_hdmi\src\dk_video.cst
-cfg E:\datasheet\gowin\TangNano4k_examples-sipeed\camera_hdmi\impl\pnr\device.cfg
-sdc E:\datasheet\gowin\TangNano4k_examples-sipeed\camera_hdmi\src\dk_video.sdc
-bit
-tr
-ph
-timing
-convert_sdp32_36_to_sdp16_18
-correct_hold 1
-route_maxfan 23
-global_freq 50.000
